# Generated by Django 3.2 on 2021-09-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('node_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(null=True)),
                ('clone_url', models.URLField(max_length=10)),
                ('size', models.IntegerField()),
                ('owner_login', models.CharField(max_length=100)),
            ],
        ),
    ]
