# Generated by Django 3.2 on 2021-09-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='url',
            field=models.URLField(default='error', max_length=10),
            preserve_default=False,
        ),
    ]
