version: "3.2"

services:
  django:
    build: ./django-app/
    volumes:
      - type: bind
        source: "./django-app"
        target: "/synker"
      - type: bind # binds to a folder on host where repos are synced into. See settings.py for more.
        source: "./repositories"
        target: "/repositories"
    
    ports:
      - "3000:3000"

    env_file:
      - './.env'
      
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn --bind :3000 --workers 3 --reload synker.wsgi:application'

